import puppeteer from 'puppeteer';

export interface PDFGenerationInput {
  summary: string;
  charts: Buffer[];
}

export async function generatePDF(input: PDFGenerationInput): Promise<Buffer> {
  console.log('📄 Generating PDF report...');

  // Create HTML content
  const html = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Data Analysis Report</title>
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }
    
    body {
      font-family: 'Courier New', monospace;
      background: #f0f0f0;
      padding: 40px;
      color: #000;
    }
    
    .container {
      max-width: 800px;
      margin: 0 auto;
      background: #fff;
      border: 5px solid #000;
      box-shadow: 10px 10px 0 #000;
    }
    
    .header {
      background: #ffeb3b;
      border-bottom: 5px solid #000;
      padding: 30px;
    }
    
    h1 {
      font-size: 36px;
      font-weight: bold;
      text-transform: uppercase;
      letter-spacing: 2px;
    }
    
    .subtitle {
      font-size: 14px;
      margin-top: 10px;
      opacity: 0.8;
    }
    
    .content {
      padding: 40px;
    }
    
    .section {
      margin-bottom: 40px;
    }
    
    .section-title {
      font-size: 24px;
      font-weight: bold;
      text-transform: uppercase;
      margin-bottom: 20px;
      padding-bottom: 10px;
      border-bottom: 3px solid #000;
    }
    
    .summary {
      background: #e8f5e9;
      border: 3px solid #000;
      padding: 20px;
      margin-bottom: 30px;
      line-height: 1.6;
      white-space: pre-wrap;
    }
    
    .chart-container {
      background: #fff;
      border: 3px solid #000;
      padding: 20px;
      margin-bottom: 30px;
      box-shadow: 5px 5px 0 #000;
    }
    
    .chart-container img {
      width: 100%;
      height: auto;
      display: block;
    }
    
    .chart-title {
      font-size: 18px;
      font-weight: bold;
      margin-bottom: 15px;
      text-align: center;
    }
    
    .footer {
      background: #000;
      color: #fff;
      padding: 20px;
      text-align: center;
      font-size: 12px;
    }
    
    .badge {
      display: inline-block;
      background: #ff5722;
      color: #fff;
      padding: 5px 15px;
      border: 2px solid #000;
      font-weight: bold;
      margin-right: 10px;
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>📊 Data Analysis Report</h1>
      <div class="subtitle">
        <span class="badge">AI-Powered</span>
        <span class="badge">E2B + Groq</span>
        Generated: ${new Date().toLocaleDateString()}
      </div>
    </div>
    
    <div class="content">
      <div class="section">
        <div class="section-title">Executive Summary</div>
        <div class="summary">${escapeHtml(input.summary)}</div>
      </div>
      
      ${input.charts.length > 0 ? `
      <div class="section">
        <div class="section-title">Visualizations (${input.charts.length})</div>
        ${input.charts.map((chart, i) => `
          <div class="chart-container">
            <div class="chart-title">Chart ${i + 1}</div>
            <img src="data:image/png;base64,${chart.toString('base64')}" alt="Chart ${i + 1}" />
          </div>
        `).join('')}
      </div>
      ` : ''}
    </div>
    
    <div class="footer">
      🤖 Generated by WhatsApp Data Analyst Agent | Powered by E2B, Groq, and Exa
    </div>
  </div>
</body>
</html>
`;

  // Launch Puppeteer and generate PDF
  const browser = await puppeteer.launch({
    headless: true,
    args: [
      '--no-sandbox',
      '--disable-setuid-sandbox',
      '--disable-dev-shm-usage',
      '--disable-gpu'
    ]
  });

  const page = await browser.newPage();
  await page.setContent(html, { waitUntil: 'networkidle0' });

  const pdfBuffer = await page.pdf({
    format: 'A4',
    printBackground: true,
    margin: {
      top: '0',
      right: '0',
      bottom: '0',
      left: '0'
    }
  });

  await browser.close();

  console.log('   ✅ PDF generated');

  return Buffer.from(pdfBuffer);
}

function escapeHtml(text: string): string {
  const map: Record<string, string> = {
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#039;'
  };
  return text.replace(/[&<>"']/g, (m) => map[m]);
}

